import { ScheduleStatus } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import type { PlannerHorizon } from "@/lib/planner/types";
import type { SolverRunInput, SolverRunResult } from "@/lib/planner/solve";

function toUtcDateOnly(value: string) {
  return new Date(`${value}T00:00:00.000Z`);
}

export async function persistGeneratedScheduleDraft(
  gymId: string,
  horizon: PlannerHorizon,
  solverInput: SolverRunInput,
  solverResult: SolverRunResult,
) {
  const startDate = toUtcDateOnly(horizon.startDate);
  const endDate = toUtcDateOnly(horizon.endDate);

  await prisma.schedule.deleteMany({
    where: {
      gymId,
      startDate,
      endDate,
      status: {
        in: [ScheduleStatus.DRAFT, ScheduleStatus.GENERATED],
      },
    },
  });

  const assignmentsByBlockId = new Map<string, string[]>();
  for (const assignment of solverResult.assignments) {
    const current = assignmentsByBlockId.get(assignment.demandBlockId) ?? [];
    current.push(assignment.employeeId);
    assignmentsByBlockId.set(assignment.demandBlockId, current);
  }

  const openDemandByBlockId = new Map(
    solverResult.openDemand.map((item) => [item.demandBlockId, item.missingStaff]),
  );

  const assignmentCount = solverResult.assignments.length;
  const openBlockCount = solverResult.openDemand.length;

  return prisma.schedule.create({
    data: {
      gymId,
      startDate,
      endDate,
      status: solverResult.status === "OPTIMAL" || solverResult.status === "FEASIBLE" ? ScheduleStatus.GENERATED : ScheduleStatus.DRAFT,
      notes: `Generated by CP-SAT (${solverResult.status}) · ${assignmentCount} assignments · ${openBlockCount} open blocks${solverResult.warnings.length ? ` · ${solverResult.warnings.join(" | ")}` : ""}`,
      shifts: {
        create: solverInput.demandBlocks.map((block) => ({
          areaId: block.areaId,
          workDate: toUtcDateOnly(block.workDate),
          startMinutes: block.startMinutes,
          endMinutes: block.endMinutes,
          minStaff: block.minStaff,
          maxStaff: block.maxStaff,
          openSlots: openDemandByBlockId.get(block.id) ?? 0,
          assignments: {
            create: (assignmentsByBlockId.get(block.id) ?? []).map((employeeId) => ({
              employeeId,
            })),
          },
        })),
      },
    },
    include: {
      shifts: {
        include: {
          assignments: true,
        },
      },
    },
  });
}
